---
title: "Background"
output: html_document
---

In response to the emergence of novel coronavirus (COVID-19), ISARIC launched a portfolio of resources to accelerate outbreak research and response. All data collection tools are designed to address the most critical public health questions, have undergone extensive review by international clinical experts, and are free for all to use. Resources are available on the [ISARIC website](https://isaric.tghn.org/).

The [ISARIC-WHO COVID-19 Case Record Form (CRF)](https://media.tghn.org/medialibrary/2020/03/ISARIC_COVID-19_CRF_V1.3_24Feb2020.pdf) enables the collection of standardised clinical data to inform patient management and the public health response. These forms should be used to collect data on suspected or confirmed cases of COVID-19. The CRF is available in multiple languages and is now in use across dozens of countries and research consortia, who are contributing data to these reports.

To support the rapid implementation of standardised data collection and reporting, ISARIC hosts a data platform that includes an electronic data capture system, a secure repository and an analytic framework. Data are entered to a web-based REDCap data management system, securely stored, and used to inform regular reports as above. Data contributors are invited to input on the methods and contents of the reports, and are provided with the R code to execute analysis on their own data in the platform. For more information, visit the ISARIC website.

Following the launch of this these open resources, ISARIC received a massive response from the health and research communities. ISARIC supports researchers to retain control of the data and samples they collect. All decisions regarding data use are made by the institutions that enter the data. We keep our contributors informed of any plans and welcome their input to ensure that we are generating the best science and promoting the interests of your patients, your institutions and your public health authorities. Feedback and suggestions are welcome at [ncov@isaric.org](ncov@isaric.org).
