---
title: "Summary Tables"
output: html_document
---


**Table 1:** Patient Characteristics



| **Description**                  | **Value**                                      |
|------------------------------|--------------------------------------------|
| Size of cohort               | `r de$N.cases`                            |
|                              |                                            |
| **By sex**                      |                                            |
| Male                         | `r de$N.males` (`r round(de$N.males/de$N.cases, 2)`)                            |
| Female                       | `r de$N.females` (`r round(de$N.females/de$N.cases, 2)`)                           |
| Unknown                      | `r de$N.sex.unknown` (`r 1-round(de$N.males/de$N.cases, 2)-round(de$N.females/de$N.cases, 2)`)                    |
|                              |                                            |
| **By outcome status**                   |                                            |
| Dead                         | `r de$N.deaths` (`r round(de$N.deaths/de$N.cases, 2)`) |
| Recovered (discharged alive) | `r de$N.recoveries` (`r round(de$N.recoveries/de$N.cases, 2)`)                          |
| Still in hospital            | `r de$N.censored` (`r round(de$N.censored/de$N.cases, 2)`)                            |
| Tranferred to another facility|  `r de$transfer.outcome` (`r round(de$transfer.outcome/de$N.cases, 2)`)                      |
| Unknown                         | `r de$unk.outcome` (`r round(de$unk.outcome/de$N.cases, 2)`
|                               |                                           |
| **By COVID-19 status**                           |                                  |
|  Positive (laboratory-confirmed)   |       `r de$cov.19.confirmed` (`r round(as.numeric(de$cov.19.confirmed)/de$N.cases, 2)`)                            |
|   Suspected                           |     `r de$cov.19.suspected` (`r round(as.numeric(de$cov.19.suspected)/de$N.cases, 2)`)                                 |
|                               |                                  |
| **By age group**                 |                                            |
| `r levels(patient.data$agegp10)[1]` | `r summary(patient.data$agegp10)[[1]]` (`r round(summary(patient.data$agegp10)[[1]]/de$N.cases, 2)`)         |
| `r levels(patient.data$agegp10)[2]` | `r summary(patient.data$agegp10)[[2]]` (`r round(summary(patient.data$agegp10)[[2]]/de$N.cases, 2)`)              |
| `r levels(patient.data$agegp10)[3]` | `r summary(patient.data$agegp10)[[3]]` (`r round(summary(patient.data$agegp10)[[3]]/de$N.cases, 2)`)              |
| `r levels(patient.data$agegp10)[4]` | `r summary(patient.data$agegp10)[[4]]` (`r round(summary(patient.data$agegp10)[[4]]/de$N.cases, 2)`)              |
| `r levels(patient.data$agegp10)[5]` | `r summary(patient.data$agegp10)[[5]]` (`r round(summary(patient.data$agegp10)[[5]]/de$N.cases, 2)`)              |
| `r levels(patient.data$agegp10)[6]` | `r summary(patient.data$agegp10)[[6]]` (`r round(summary(patient.data$agegp10)[[6]]/de$N.cases, 2)`)              |
| `r levels(patient.data$agegp10)[7]` | `r summary(patient.data$agegp10)[[7]]` (`r round(summary(patient.data$agegp10)[[7]]/de$N.cases, 2)`)              |
| `r levels(patient.data$agegp10)[8]` | `r summary(patient.data$agegp10)[[8]]` (`r round(summary(patient.data$agegp10)[[8]]/de$N.cases, 2)`)             |
| Unknown                      | `r summary(patient.data$agegp10)[[9]]` (`r round(summary(patient.data$agegp10)[[9]]/de$N.cases, 2)`)              |
                        

<br /><br /><br />


**Table 2:** Prevalence of Symptoms, Comorbidities and Treatments

| **Symptoms**                      | **Present**                                                               | **Absent**                        | **Unknown**                        |
|-------------------------------|-------------------------------------------------------------------------------|-------------------------------|--------------------------------|
| Abdominal pain                | `r de$s.dat$present[1]` (`r round(de$s.dat$present[1]/de$N.cases, 2)`) | `r de$s.dat$absent[1]` (`r round(de$s.dat$absent[1]/de$N.cases, 2)`)  | `r de$s.dat$unknown[1]` (`r round(de$s.dat$unknown[1]/de$N.cases, 2)`)        |
| Bleeding                      | `r de$s.dat$present[2]` (`r round(de$s.dat$present[2]/de$N.cases, 2)`) | `r de$s.dat$absent[2]` (`r round(de$s.dat$absent[2]/de$N.cases, 2)`)       | `r de$s.dat$unknown[2]` (`r round(de$s.dat$unknown[2]/de$N.cases, 2)`)         |
| Chest pain                    | `r de$s.dat$present[3]` (`r round(de$s.dat$present[3]/de$N.cases, 2)`)| `r de$s.dat$absent[3]` (`r round(de$s.dat$absent[3]/de$N.cases, 2)`)        | `r de$s.dat$unknown[3]` (`r round(de$s.dat$unknown[3]/de$N.cases, 2)`)         |
| Confusion                     | `r de$s.dat$present[4]` (`r round(de$s.dat$present[4]/de$N.cases, 2)`)        | `r de$s.dat$absent[4]` (`r round(de$s.dat$absent[4]/de$N.cases, 2)`)       | `r de$s.dat$unknown[4]` (`r round(de$s.dat$unknown[4]/de$N.cases, 2)`)         |
| Conjuctivitis                 | `r de$s.dat$present[5]` (`r round(de$s.dat$present[5]/de$N.cases, 2)`)        | `r de$s.dat$absent[5]` (`r round(de$s.dat$absent[5]/de$N.cases, 2)`)       | `r de$s.dat$unknown[5]` (`r round(de$s.dat$unknown[5]/de$N.cases, 2)`)         |
| Cough                         | `r de$cough_pre`        (`r round(de$cough_pre/de$N.cases, 2)`)               | `r de$cough_abs` (`r round(de$cough_abs/de$N.cases, 2)`) | `r de$cough_unk` (`r round(de$cough_unk/de$N.cases, 2)`)  |
| Diarrhoea                     | `r de$s.dat$present[9]` (`r round(de$s.dat$present[9]/de$N.cases, 2)`)        | `r de$s.dat$absent[9]` (`r round(de$s.dat$absent[9]/de$N.cases, 2)`)        | `r de$s.dat$unknown[9]` (`r round(de$s.dat$unknown[9]/de$N.cases, 2)`)         |
| Ear pain                      | `r de$s.dat$present[10]` (`r round(de$s.dat$present[10]/de$N.cases, 2)`)        | `r de$s.dat$absent[10]` (`r round(de$s.dat$absent[10]/de$N.cases, 2)`)       | `r de$s.dat$unknown[10]` (`r round(de$s.dat$unknown[10]/de$N.cases, 2)`)        |
| Fatigue                       | `r de$s.dat$present[11]` (`r round(de$s.dat$present[11]/de$N.cases, 2)`)        | `r de$s.dat$absent[11]` (`r round(de$s.dat$absent[11]/de$N.cases, 2)`)       | `r de$s.dat$unknown[11]` (`r round(de$s.dat$unknown[11]/de$N.cases, 2)`)       |
| Fever                         | `r de$s.dat$present[12]` (`r round(de$s.dat$present[12]/de$N.cases, 2)`)       | `r de$s.dat$absent[12]` (`r round(de$s.dat$absent[12]/de$N.cases, 2)`)       | `r de$s.dat$unknown[12]` (`r round(de$s.dat$unknown[12]/de$N.cases, 2)`)       |
| Headache                      | `r de$s.dat$present[13]` (`r round(de$s.dat$present[13]/de$N.cases, 2)`)       | `r de$s.dat$absent[13]` (`r round(de$s.dat$absent[13]/de$N.cases, 2)`)       | `r de$s.dat$unknown[13]` (`r round(de$s.dat$unknown[13]/de$N.cases, 2)`)        |
| Joint pain                    | `r de$s.dat$present[14]` (`r round(de$s.dat$present[14]/de$N.cases, 2)`)       | `r de$s.dat$absent[14]` (`r round(de$s.dat$absent[14]/de$N.cases, 2)`)      | `r de$s.dat$unknown[14]` (`r round(de$s.dat$unknown[14]/de$N.cases, 2)`)       |
| Lymph                         | `r de$s.dat$present[15]` (`r round(de$s.dat$present[15]/de$N.cases, 2)`)       | `r de$s.dat$absent[15]` (`r round(de$s.dat$absent[15]/de$N.cases, 2)`)      | `r de$s.dat$unknown[15]` (`r round(de$s.dat$unknown[15]/de$N.cases, 2)`)       |
| Myalgia                       | `r de$s.dat$present[16]` (`r round(de$s.dat$present[16]/de$N.cases, 2)`)       | `r de$s.dat$absent[16]` (`r round(de$s.dat$absent[16]/de$N.cases, 2)`)     | `r de$s.dat$unknown[16]` (`r round(de$s.dat$unknown[16]/de$N.cases, 2)`)       |
| Rash                          | `r de$s.dat$present[17]` (`r round(de$s.dat$present[17]/de$N.cases, 2)`)       | `r de$s.dat$absent[17]` (`r round(de$s.dat$absent[17]/de$N.cases, 2)`)       | `r de$s.dat$unknown[17]` (`r round(de$s.dat$unknown[17]/de$N.cases, 2)`)       |
| Runny nose                    | `r de$s.dat$present[18]` (`r round(de$s.dat$present[18]/de$N.cases, 2)`)       | `r de$s.dat$absent[18]` (`r round(de$s.dat$absent[18]/de$N.cases, 2)`)       | `r de$s.dat$unknown[18]` (`r round(de$s.dat$unknown[18]/de$N.cases, 2)`)       |
| Seizures                      | `r de$s.dat$present[19]`  (`r round(de$s.dat$present[19]/de$N.cases, 2)`)      | `r de$s.dat$absent[19]` (`r round(de$s.dat$absent[19]/de$N.cases, 2)`)       | `r de$s.dat$unknown[19]` (`r round(de$s.dat$unknown[19]/de$N.cases, 2)`)       |
| Shortness of breath           | `r de$s.dat$present[20]`   (`r round(de$s.dat$present[20]/de$N.cases, 2)`)     | `r de$s.dat$absent[20]` (`r round(de$s.dat$absent[20]/de$N.cases, 2)`)       | `r de$s.dat$unknown[20]` (`r round(de$s.dat$unknown[20]/de$N.cases, 2)`)       |
|                               |                                |                               |                                |
| **Comorbidities**                 |                                |                               |                                |
| AIDS/HIV                      | `r de$c.dat$present[1]` (`r round(de$c.dat$present[1]/de$N.cases, 2)`)         | `r de$c.dat$absent[1]` (`r round(de$c.dat$absent[1]/de$N.cases, 2)`)        | `r de$c.dat$unknown[1]` (`r round(de$c.dat$unknown[1]/de$N.cases, 2)`)         |
| Asthma                        | `r de$c.dat$present[2]` (`r round(de$c.dat$present[2]/de$N.cases, 2)`)       | `r de$c.dat$absent[2]` (`r round(de$c.dat$absent[2]/de$N.cases, 2)`)         | `r de$c.dat$unknown[2]` (`r round(de$c.dat$unknown[2]/de$N.cases, 2)`)        |
| Chronic cardiac disease       | `r de$c.dat$present[3]` (`r round(de$c.dat$present[3]/de$N.cases, 2)`)       | `r de$c.dat$absent[3]` (`r round(de$c.dat$absent[3]/de$N.cases, 2)`)        | `r de$c.dat$unknown[3]` (`r round(de$c.dat$unknown[3]/de$N.cases, 2)`)        |
| Chronic haematologic disease  | `r de$c.dat$present[4]` (`r round(de$c.dat$present[4]/de$N.cases, 2)`)      | `r de$c.dat$absent[4]` (`r round(de$c.dat$absent[4]/de$N.cases, 2)`)       | `r de$c.dat$unknown[4]` (`r round(de$c.dat$unknown[4]/de$N.cases, 2)`)        |
| Chronic neurological disorder | `r de$c.dat$present[5]` (`r round(de$c.dat$present[5]/de$N.cases, 2)`)      | `r de$c.dat$absent[5]` (`r round(de$c.dat$absent[5]/de$N.cases, 2)`)       | `r de$c.dat$unknown[5]` (`r round(de$c.dat$unknown[5]/de$N.cases, 2)`)        |
| Chronic pulmonary disease     | `r de$c.dat$present[6]` (`r round(de$c.dat$present[6]/de$N.cases, 2)`)      | `r de$c.dat$absent[6]` (`r round(de$c.dat$absent[6]/de$N.cases, 2)`)       | `r de$c.dat$unknown[6]` (`r round(de$c.dat$unknown[6]/de$N.cases, 2)`)        |
| Dementia                      | `r de$c.dat$present[7]` (`r round(de$c.dat$present[7]/de$N.cases, 2)`)       | `r de$c.dat$absent[7]` (`r round(de$c.dat$absent[7]/de$N.cases, 2)`)        | `r de$c.dat$unknown[7]` (`r round(de$c.dat$unknown[7]/de$N.cases, 2)`)        |
| Diabetes                      | `r de$c.dat$present[8]` (`r round(de$c.dat$present[8]/de$N.cases, 2)`)       | `r de$c.dat$absent[8]` (`r round(de$c.dat$absent[8]/de$N.cases, 2)`)        | `r de$c.dat$unknown[8]` (`r round(de$c.dat$unknown[8]/de$N.cases, 2)`)        |
| Liver disease                 | `r de$c.dat$present[9]` (`r round(de$c.dat$present[9]/de$N.cases, 2)`)       | `r de$c.dat$absent[9]` (`r round(de$c.dat$absent[9]/de$N.cases, 2)`)        | `r de$c.dat$unknown[9]` (`r round(de$c.dat$unknown[9]/de$N.cases, 2)`)        |
| Malignant neoplasm            | `r de$c.dat$present[10]` (`r round(de$c.dat$present[10]/de$N.cases, 2)`)      | `r de$c.dat$absent[10]` (`r round(de$c.dat$absent[10]/de$N.cases, 2)`)       | `r de$c.dat$unknown[10]` (`r round(de$c.dat$unknown[10]/de$N.cases, 2)`)       |
| Malnutrition                  | `r de$c.dat$present[11]` (`r round(de$c.dat$present[11]/de$N.cases, 2)`)       | `r de$c.dat$absent[11]` (`r round(de$c.dat$absent[11]/de$N.cases, 2)`)        | `r de$c.dat$unknown[11]` (`r round(de$c.dat$unknown[11]/de$N.cases, 2)`)       |
| Obesity                       | `r de$c.dat$present[12]` (`r round(de$c.dat$present[12]/de$N.cases, 2)`)      | `r de$c.dat$absent[12]` (`r round(de$c.dat$absent[12]/de$N.cases, 2)`)       | `r de$c.dat$unknown[12]` (`r round(de$c.dat$unknown[12]/de$N.cases, 2)`)       |
| Chronic kidney disease        | `r de$c.dat$present[14]` (`r round(de$c.dat$present[14]/de$N.cases, 2)`)      | `r de$c.dat$absent[14]` (`r round(de$c.dat$absent[14]/de$N.cases, 2)`)       | `r de$c.dat$unknown[14]` (`r round(de$c.dat$unknown[14]/de$N.cases, 2)`)       |
| Rheumatologic disorder        | `r de$c.dat$present[15]` (`r round(de$c.dat$present[15]/de$N.cases, 2)`)      | `r de$c.dat$absent[15]` (`r round(de$c.dat$absent[15]/de$N.cases, 2)`)       | `r de$c.dat$unknown[15]` (`r round(de$c.dat$unknown[15]/de$N.cases, 2)`)       |
| Smoking                       | `r de$c.dat$present[16]` (`r round(de$c.dat$present[16]/de$N.cases, 2)`)      | `r de$c.dat$absent[16]` (`r round(de$c.dat$absent[16]/de$N.cases, 2)`)       | `r de$c.dat$unknown[16]` (`r round(de$c.dat$unknown[16]/de$N.cases, 2)`)       |
| Other risk factors            | `r de$c.dat$present[13]` (`r round(de$c.dat$present[13]/de$N.cases, 2)`)      | `r de$c.dat$absent[13]` (`r round(de$c.dat$absent[13]/de$N.cases, 2)`)       | `r de$c.dat$unknown[13]`  (`r round(de$c.dat$unknown[13]/de$N.cases, 2)`)      |
|                               |                                |                               |                                |
| **Treatment**                     |                                |                               |                                |
| Antibiotic agent              | `r de$t.dat$present[1]` (`r round(de$t.dat$present[1]/de$N.cases, 2)`)        | `r de$t.dat$absent[1]` (`r round(de$IMV.ab/de$N.cases, 2)`)   | `r de$t.dat$unknown[1]` (`r round(de$t.dat$unknown[1]/de$N.cases, 2)`)        |
| Antifungal agent              | `r de$t.dat$present[2]`  (`r round(de$t.dat$present[2]/de$N.cases, 2)`)       | `r de$t.dat$absent[2]` (`r round(de$t.dat$absent[2]/de$N.cases, 2)`)      | `r de$t.dat$unknown[2]` (`r round(de$t.dat$unknown[2]/de$N.cases, 2)`)           |
| Antiviral agent               | `r de$t.dat$present[3]`  (`r round(de$t.dat$present[3]/de$N.cases, 2)`)       | `r de$t.dat$absent[3]` (`r round(de$t.dat$absent[3]/de$N.cases, 2)`)       | `r de$t.dat$unknown[3]` (`r round(de$t.dat$unknown[3]/de$N.cases, 2)`)          |
| Corticosteroid agent          | `r de$t.dat$present[4]`  (`r round(de$t.dat$present[4]/de$N.cases, 2)`)       | `r de$t.dat$absent[4]` (`r round(de$t.dat$absent[4]/de$N.cases, 2)`)       | `r de$t.dat$unknown[4]` (`r round(de$t.dat$unknown[4]/de$N.cases, 2)`)           |
| Extracorporeal support        | `r de$t.dat$present[5]`  (`r round(de$t.dat$present[5]/de$N.cases, 2)`)       | `r de$t.dat$absent[5]` (`r round(de$t.dat$absent[5]/de$N.cases, 2)`)       | `r de$t.dat$unknown[5]` (`r round(de$t.dat$unknown[5]/de$N.cases, 2)`)          |
| Inhaled nitric oxide          | `r de$t.dat$present[6]`  (`r round(de$t.dat$present[6]/de$N.cases, 2)`)       | `r de$t.dat$absent[6]` (`r round(de$t.dat$absent[6]/de$N.cases, 2)`)       | `r de$t.dat$unknown[6]`  (`r round(de$t.dat$unknown[6]/de$N.cases, 2)`)          |
| Inotropes / vasopressors      | `r de$t.dat$present[7]`   (`r round(de$t.dat$present[7]/de$N.cases, 2)`)      | `r de$t.dat$absent[7]` (`r round(de$t.dat$absent[7]/de$N.cases, 2)`)       | `r de$t.dat$unknown[7]`  (`r round(de$t.dat$unknown[7]/de$N.cases, 2)`)          |
| Invasive ventilation          | `r de$IMV.pr` (`r round(de$IMV.pr/de$N.cases, 2)`)                  | `r de$IMV.ab` (`r round(de$IMV.ab/de$N.cases, 2)`)        | `r de$IMV.un` (`r round(de$IMV.un/de$N.cases, 2)`)        |
| Non-invasive ventilation      | `r de$NIMV.pr` (`r round(de$NIMV.pr/de$N.cases, 2)`)                  | `r de$NIMV.ab` (`r round(de$NIMV.ab/de$N.cases, 2)`)            | `r de$NIMV.un` (`r round(de$NIMV.un/de$N.cases, 2)`)        |
| Oxygen therapy                | `r de$o2.pr` (`r round(de$o2.pr/de$N.cases, 2)`)                 | `r de$o2.ab`  (`r round(de$o2.ab/de$N.cases, 2)`)             | `r de$o2.un` (`r round(de$o2.un/de$N.cases, 2)`)       |
| Prone ventilation             | `r de$t.dat$present[12]`  (`r round(de$t.dat$present[12]/de$N.cases, 2)`)      | `r de$t.dat$absent[12]` (`r round(de$t.dat$absent[12]/de$N.cases, 2)`)      | `r de$t.dat$unknown[12]` (`r round(de$t.dat$unknown[12]/de$N.cases, 2)`)         |
| Renal replacement therapy     | `r de$t.dat$present[13]`  (`r round(de$t.dat$present[13]/de$N.cases, 2)`)      | `r de$t.dat$absent[13]` (`r round(de$t.dat$absent[13]/de$N.cases, 2)`)      | `r de$t.dat$unknown[13]` (`r round(de$t.dat$unknown[13]/de$N.cases, 2)`)         |
| Tracheostomy inserted         | `r de$t.dat$present[14]`  (`r round(de$t.dat$present[14]/de$N.cases, 2)`)      | `r de$t.dat$absent[14]` (`r round(de$t.dat$absent[14]/de$N.cases, 2)`)      | `r de$t.dat$unknown[14]` (`r round(de$t.dat$unknown[14]/de$N.cases, 2)`)          |
| Other                         | `r de$t.dat$present[10]`  (`r round(de$t.dat$present[10]/de$N.cases, 2)`)      | `r de$t.dat$absent[10]` (`r round(de$t.dat$absent[10]/de$N.cases, 2)`)      | `r de$t.dat$unknown[10]` (`r round(de$t.dat$unknown[10]/de$N.cases, 2)`)        |
| Extracorporeal membrane oxygenation (ECMO) | `r de$ECMO.pr`  (`r round(de$ECMO.pr/de$N.cases, 2)`)| `r de$ECMO.ab` (`r round(de$ECMO.ab/de$N.cases, 2)`) | `r de$ECMO.un` (`r round(de$ECMO.un/de$N.cases, 2)`)|

<br /><br /><br />

\newpage


**Table 3:** Key time variables.

Unlike the observed mean, the estimation process of the **expected mean** accounts for all cases, irrespective of whether an outcome has been observed. The expected mean is 'NA' for those variables for which parameter estimation could not be performed, due to the high proportion of unobserved end dates. The interquartile range is abbbreviated 'IQR'. 




| Time (in days)             | Mean (observed)                        | SD (observed )                       | Median (observed)                        | IQR (observed )                       | Expected mean (95% CI)                                             |
|----------------------------|----------------------------------------|--------------------------------------|------------------------------------------|---------------------------------------|--------------------------------------------------------------------|
| Length of hospital stay    | `r de$obs.mean.adm.outcome`            | `r de$obs.sd.adm.outcome`            | `r de$obs.median.adm.outcome`            | `r de$obs.iqr.adm.outcome`            | `r de$adm.to.outcome` (`r de$adm.outcome.l`, `r de$adm.outcome.u`) |
| Symptom onset to admission | `r  de$obs.mean.onset.adm`             | `r de$obs.sd.onset.adm`              | `r  de$obs.median.onset.adm`             | `r de$obs.iqr.onset.adm`              | `r de$onset.to.adm` (`r de$onset.to.adm.l`, `r de$onset.to.adm.u`) |
|                            |                                        |                                      |                                          |                                       |                                                                    |
| Admission to ICU entry     | `r round(mean(de$a.icu, na.rm=T), 1)`  | `r round(sd(de$a.icu, na.rm=T), 1)`  | `r round(median(de$a.icu, na.rm=T), 1)`  | `r round(IQR(de$a.icu, na.rm=T), 1)`  | `r de$adm.icu` (`r de$adm.icu.l`, `r  de$adm.icu.u`)               |
| Duration of ICU            | `r round(mean(de$d.icu, na.rm=T), 1)`  | `r round(sd(de$d.icu, na.rm=T), 1)`  | `r round(median(de$d.icu, na.rm=T), 1)`  | `r round(IQR(de$d.icu, na.rm=T), 1)`  | NA                                                                 |
|                            |                                        |                                      |                                          |                                       |                                                                    |
| Admission to IMV           | `r round(mean(de$a.imv, na.rm=T), 1)`  | `r round(sd(de$a.imv, na.rm=T), 1)`  | `r round(median(de$a.imv, na.rm=T), 1)`  | `r round(IQR(de$a.imv, na.rm=T), 1)`  | `r de$adm.imv` (`r  de$adm.imv.l`, `r  de$adm.imv.u`)              |
| Duration of IMV            | `r round(mean(de$d.imv, na.rm=T), 1)`  | `r round(sd(de$d.imv, na.rm=T), 1)`  | `r round(median(de$d.imv, na.rm=T), 1)`  | `r round(IQR(de$d.imv, na.rm=T), 1)`  | NA                                                                 |
|                            |                                        |                                      |                                          |                                       |                                                                    |
| Admission to NIV           | `r round(mean(de$a.nimv, na.rm=T), 1)` | `r round(sd(de$a.nimv, na.rm=T), 1)` | `r round(median(de$a.nimv, na.rm=T), 1)` | `r round(IQR(de$a.nimv, na.rm=T), 1)` | `r de$adm.niv` (`r  de$adm.niv.l`, `r  de$adm.niv.u`)              |
| Duration of NIV            | `r round(mean(de$d.nimv, na.rm=T), 1)` | `r round(sd(de$d.nimv, na.rm=T), 1)` | `r round(median(de$d.nimv, na.rm=T), 1)` | `r round(IQR(de$a.nimv, na.rm=T), 1)` | NA              |



















<!-- | Time (in days)             |                                                                        Observed statistics  |           Expected mean (95% CI)                           | -->
<!-- |----------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------:|:--------------------------------------------------------------------:| -->
<!-- |                            | Mean                                   | SD                                   | Median                                   | IQR                                   |                                            | -->
<!-- | Length of hospital stay    | `r de$obs.mean.adm.outcome`            | `r de$obs.sd.adm.outcome`            | `r de$obs.median.adm.outcome`            | `r de$obs.iqr.adm.outcome`            | `r de$adm.to.outcome` (`r de$adm.outcome.l`, `r de$adm.outcome.u`) | -->
<!-- | Symptom onset to admission | `r  de$obs.mean.onset.adm`             | `r de$obs.sd.onset.adm`              | `r  de$obs.median.onset.adm`             | `r de$obs.iqr.onset.adm`              | `r de$onset.to.adm` (`r de$onset.to.adm.l`, `r de$onset.to.adm.u`) | -->
<!-- |                            |                                        |                                      |                                          |                                       |                                                                    | -->
<!-- | Admission to ICU entry     | `r round(mean(de$a.icu, na.rm=T), 1)`  | `r round(sd(de$a.icu, na.rm=T), 1)`  | `r round(median(de$a.icu, na.rm=T), 1)`  | `r round(IQR(de$a.icu, na.rm=T), 1)`  | `r de$adm.icu` (`r de$adm.icu.l`, `r  de$adm.icu.u`)               | -->
<!-- | Duration of ICU            | `r round(mean(de$d.icu, na.rm=T), 1)`  | `r round(sd(de$d.icu, na.rm=T), 1)`  | `r round(median(de$d.icu, na.rm=T), 1)`  | `r round(IQR(de$d.icu, na.rm=T), 1)`  | NA                                                                 | -->
<!-- |                            |                                        |                                      |                                          |                                       |                                                                    | -->
<!-- | Admission to IMV           | `r round(mean(de$a.imv, na.rm=T), 1)`  | `r round(sd(de$a.imv, na.rm=T), 1)`  | `r round(median(de$a.imv, na.rm=T), 1)`  | `r round(IQR(de$a.imv, na.rm=T), 1)`  | `r de$adm.imv` (`r  de$adm.imv.l`, `r  de$adm.imv.u`)              | -->
<!-- | Duration of IMV            | `r round(mean(de$d.imv, na.rm=T), 1)`  | `r round(sd(de$d.imv, na.rm=T), 1)`  | `r round(median(de$d.imv, na.rm=T), 1)`  | `r round(IQR(de$d.imv, na.rm=T), 1)`  | NA                                                                 | -->
<!-- |                            |                                        |                                      |                                          |                                       |                                                                    | -->
<!-- | Admission to NIV           | `r round(mean(de$a.nimv, na.rm=T), 1)` | `r round(sd(de$a.nimv, na.rm=T), 1)` | `r round(median(de$a.nimv, na.rm=T), 1)` | `r round(IQR(de$a.nimv, na.rm=T), 1)` | `r de$adm.niv` (`r  de$adm.niv.l`, `r  de$adm.niv.u`)              | -->
<!-- | Duration of NIV            | `r round(mean(de$d.nimv, na.rm=T), 1)` | `r round(sd(de$d.nimv, na.rm=T), 1)` | `r round(median(de$d.nimv, na.rm=T), 1)` | `r round(IQR(de$a.nimv, na.rm=T), 1)` | `r de$dur.niv` (`r  de$dur.niv.l`, `r  de$dur.niv.u`)              | -->






























<!-- | Time (in days)             | Observed mean                          | Observed SD                          | Observed median                          |  Observed IQR     | Expected mean (95% CI)                                             | -->
<!-- |----------------------------|----------------------------------------|--------------------------------------|------------------------------------------|--------|--------------------------------------------------------------------| -->
<!-- | Length of hospital stay    | `r de$obs.mean.adm.outcome`            | `r de$obs.sd.adm.outcome`            | `r de$obs.median.adm.outcome`            | `r de$obs.iqr.adm.outcome`         |`r de$adm.to.outcome` (`r de$adm.outcome.l`, `r de$adm.outcome.u`) | -->
<!-- | Symptom onset to admission | `r  de$obs.mean.onset.adm`             | `r de$obs.sd.onset.adm`              | `r  de$obs.median.onset.adm`             |  `r de$obs.iqr.onset.adm`        |`r de$onset.to.adm` (`r de$onset.to.adm.l`, `r de$onset.to.adm.u`) | -->
<!-- |                            |                                        |                                      |                                          |          |                                                                  | -->
<!-- | Admission to ICU entry     | `r round(mean(de$a.icu, na.rm=T), 1)`  | `r round(sd(de$a.icu, na.rm=T), 1)`  | `r round(median(de$a.icu, na.rm=T), 1)`  |  `r round(IQR(de$a.icu, na.rm=T), 1)`        |    `r de$adm.icu` (`r de$adm.icu.l`, `r de$adm.icu.u`)                      | -->
<!-- | Duration of ICU            | `r round(mean(de$d.icu, na.rm=T), 1)`  | `r round(sd(de$d.icu, na.rm=T), 1)`  | `r round(median(de$d.icu, na.rm=T), 1)`  |   `r round(IQR(de$d.icu, na.rm=T), 1)`      |NA                                                                 | -->
<!-- |                            |                                        |                                      |                                          |          |                                                                  | -->
<!-- | Admission to IMV           | `r round(mean(de$a.imv, na.rm=T), 1)`  | `r round(sd(de$a.imv, na.rm=T), 1)`  | `r round(median(de$a.imv, na.rm=T), 1)`  |   `r round(IQR(de$a.imv, na.rm=T), 1)`       |`r de$adm.imv` (`r de$adm.imv.l`, `r de$adm.imv.u`)                      | -->
<!-- | Duration of IMV            | `r round(mean(de$d.imv, na.rm=T), 1)`  | `r round(sd(de$d.imv, na.rm=T), 1)`  | `r round(median(de$d.imv, na.rm=T), 1)`  |     `r round(IQR(de$d.imv, na.rm=T), 1)`     |NA                                                                 | -->
<!-- |                            |                                        |                                      |                                          |          |                                                                  | -->
<!-- | Admission to NIV           | `r round(mean(de$a.nimv, na.rm=T), 1)` | `r round(sd(de$a.nimv, na.rm=T), 1)` | `r round(median(de$a.nimv, na.rm=T), 1)` |   `r round(IQR(de$a.nimv, na.rm=T), 1)`       |`r de$adm.niv` (`r de$adm.niv.l`, `r de$adm.niv.u`)                      | -->
<!-- | Duration of NIV            | `r round(mean(de$d.nimv, na.rm=T), 1)` | `r round(sd(de$d.nimv, na.rm=T), 1)` | `r round(median(de$d.nimv, na.rm=T), 1)` |     `r round(IQR(de$a.nimv, na.rm=T), 1)`     |`r de$dur.niv` (`r de$dur.niv.l`, `r de$dur.niv.u`)                      | -->










