---
title: "Background"
output: html_document
---

In response to the emergence of novel coronavirus (COVID-19), ISARIC launched a portfolio of resources to accelerate outbreak research and response. These include data collection, analysis and presentation tools which are freely available to all sites which have requested access to these resources. All data collection tools are designed to address the most critical public health questions, have undergone extensive review by international clinical experts, and are free for all to use. Resources are available on the [ISARIC website](https://isaric.tghn.org/).

The [ISARIC-WHO COVID-19 Case Record Form (CRF)](https://media.tghn.org/medialibrary/2020/03/ISARIC_COVID-19_CRF_V1.3_24Feb2020.pdf) enables the collection of standardised clinical data to inform patient management and public health response. These forms should be used to collect data on suspected or confirmed cases of COVID-19. The CRF is available in multiple languages and is now in use across dozens of countries and research consortia, who are contributing data to these reports.

To support researchers to retain control of the data and samples they collect, ISARIC also hosts a data platform, where data can be entered to a web-based REDCap data management system, securely stored, and used to produce regular reports on their sites as above. Data contributors are invited to input on the methods and contents of the reports, and can also contribute to the aggregated data platform which aggregates site-specific data from all other sites across the world who are using this system. For more information, visit the ISARIC website. 

All decisions regarding data use are made by the institutions that enter the data. ISARIC keeps contributors informed of any plans and welcomes their input to promote the best science and the interests of patients, institutions and public health authorities. Feedback and suggestions are welcome at [ncov@isaric.org](ncov@isaric.org).
